language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1  
before_script:
  - pear config-set auto_discover 1
  - pear install pear.phing.info/phing
  - phpenv rehash
script: phing travisci
